CREATE TABLE IF NOT EXISTS auth_permission (
    `Column_1` INT,
    `Column_2` VARCHAR(31) CHARACTER SET utf8,
    `Column_3` INT,
    `Column_4` VARCHAR(25) CHARACTER SET utf8
);
INSERT INTO auth_permission VALUES
    (1,'Can add saved_ recipes',1,'add_saved_recipes'),
    (2,'Can change saved_ recipes',1,'change_saved_recipes'),
    (3,'Can delete saved_ recipes',1,'delete_saved_recipes'),
    (4,'Can add preference cuisines',2,'add_preferencecuisines'),
    (5,'Can change preference cuisines',2,'change_preferencecuisines'),
    (6,'Can delete preference cuisines',2,'delete_preferencecuisines'),
    (7,'Can add preference raw foods',3,'add_preferencerawfoods'),
    (8,'Can change preference raw foods',3,'change_preferencerawfoods'),
    (9,'Can delete preference raw foods',3,'delete_preferencerawfoods'),
    (10,'Can add intolerences',4,'add_intolerences'),
    (11,'Can change intolerences',4,'change_intolerences'),
    (12,'Can delete intolerences',4,'delete_intolerences'),
    (13,'Can add usd afoods',5,'add_usdafoods'),
    (14,'Can change usd afoods',5,'change_usdafoods'),
    (15,'Can delete usd afoods',5,'delete_usdafoods'),
    (16,'Can add user db',6,'add_userdb'),
    (17,'Can change user db',6,'change_userdb'),
    (18,'Can delete user db',6,'delete_userdb'),
    (19,'Can add feedback',7,'add_feedback'),
    (20,'Can change feedback',7,'change_feedback'),
    (21,'Can delete feedback',7,'delete_feedback'),
    (22,'Can add feedback raw food',8,'add_feedbackrawfood'),
    (23,'Can change feedback raw food',8,'change_feedbackrawfood'),
    (24,'Can delete feedback raw food',8,'delete_feedbackrawfood'),
    (25,'Can add recipe',9,'add_recipe'),
    (26,'Can change recipe',9,'change_recipe'),
    (27,'Can delete recipe',9,'delete_recipe'),
    (28,'Can add log entry',10,'add_logentry'),
    (29,'Can change log entry',10,'change_logentry'),
    (30,'Can delete log entry',10,'delete_logentry'),
    (31,'Can add permission',11,'add_permission'),
    (32,'Can change permission',11,'change_permission'),
    (33,'Can delete permission',11,'delete_permission'),
    (34,'Can add user',12,'add_user'),
    (35,'Can change user',12,'change_user'),
    (36,'Can delete user',12,'delete_user'),
    (37,'Can add group',13,'add_group'),
    (38,'Can change group',13,'change_group'),
    (39,'Can delete group',13,'delete_group'),
    (40,'Can add content type',14,'add_contenttype'),
    (41,'Can change content type',14,'change_contenttype'),
    (42,'Can delete content type',14,'delete_contenttype'),
    (43,'Can add session',15,'add_session'),
    (44,'Can change session',15,'change_session'),
    (45,'Can delete session',15,'delete_session');
