CREATE TABLE IF NOT EXISTS feedbackrawfood (
    `Column_1` INT,
    `Column_2` INT,
    `Column_3` VARCHAR(106) CHARACTER SET utf8,
    `Column_4` VARCHAR(27) CHARACTER SET utf8,
    `Column_5` VARCHAR(8) CHARACTER SET utf8,
    `Column_6` VARCHAR(9) CHARACTER SET utf8,
    `Column_7` INT,
    `Column_8` INT
);
INSERT INTO feedbackrawfood VALUES
    (1,4,'DIGIORNO Pizza, supreme topping, rising crust, frozen, baked','21479','1',NULL,NULL,NULL),
    (2,4,'Grape juice drink, canned','14282','1',NULL,NULL,NULL),
    (3,4,'Cereals ready-to-eat, QUAKER, Cap''n Crunch''s OOPS! All Berries Cereal','8629','1',NULL,NULL,NULL),
    (4,4,'KELLOGG''S, POP-TARTS, Frosted Spring Berry Toaster Pastries','28172','1',NULL,NULL,NULL),
    (5,4,'Tea, herbal, brewed, Hohoysi (Hopi)','35238','3',NULL,NULL,NULL),
    (6,4,'Cheese, monterey, low fat','42155','3',NULL,NULL,NULL),
    (7,4,'SUNSHINE, CHEEZ-IT, 100 Calorie RIGHT BITES, Extra Cheesy Party Mix','28250','3',NULL,NULL,NULL),
    (8,4,'Beef, brisket, flat half, separable lean and fat, trimmed to 1/8\ fat',' choice',' cooked',' braised"',23660,3),
    (9,4,'SPAGHETTIOS, SpaghettiOs plus Calcium','22938','3',NULL,NULL,NULL),
    (10,4,'Cauliflower, frozen, cooked, boiled, drained, without salt','11138','3',NULL,NULL,NULL),
    (11,4,'Cereals ready-to-eat, POST, ALPHA-BITS','8002','3',NULL,NULL,NULL),
    (12,4,'Fish, tuna salad','15128','3',NULL,NULL,NULL),
    (13,4,'Turnip greens and turnips, frozen, unprepared','11576','4',NULL,NULL,NULL),
    (14,4,'Soybeans, mature seeds, sprouted, cooked, stir-fried, with salt','11924','4',NULL,NULL,NULL),
    (15,4,'Bread, reduced-calorie, oat bran','18049','4',NULL,NULL,NULL),
    (16,4,'KEEBLER, ANIMALS, Iced Cookies','28045','4',NULL,NULL,NULL),
    (17,4,'Pork, ground, 84% lean / 16% fat, raw','10972','4',NULL,NULL,NULL),
    (18,4,'Veal, breast, whole, boneless, separable lean and fat, raw','17271','4',NULL,NULL,NULL),
    (19,4,'Babyfood, fruit, prunes with tapioca, without ascorbic acid, strained','3136','4',NULL,NULL,NULL),
    (20,4,'Milk, chocolate, fat free, with added vitamin A and vitamin D','1292','4',NULL,NULL,NULL),
    (21,4,'Beef, chuck for stew, separable lean and fat, select, raw','23094','5',NULL,NULL,NULL),
    (22,4,'Beef, round, top round steak, boneless, separable lean only, trimmed to 0\ fat',' select',' raw"','23356',5,NULL),
    (23,4,'Beef, loin, bottom sirloin butt, tri-tip roast, separable lean only, trimmed to 0\ fat',' all grades',' cooked',' roasted"',13985,5),
    (24,4,'Beef, round, top round, steak, separable lean and fat, trimmed to 1/8\ fat',' prime',' cooked',' broiled"',13902,5),
    (25,4,'Cookies, peanut butter, commercially prepared, sugar free','28301','6',NULL,NULL,NULL),
    (26,4,'Turkey, mechanically deboned, from turkey frames, raw','5304','6',NULL,NULL,NULL),
    (27,4,'Beef, shoulder pot roast or steak, boneless, separable lean and fat, trimmed to 0\ fat',' choice',' raw"','23111',6,NULL),
    (28,4,'Seeds, sunflower seed kernels, dry roasted, with salt added','12537','6',NULL,NULL,NULL),
    (29,4,'Octopus (Alaska Native)','35054','8',NULL,NULL,NULL),
    (30,4,'Chicken, roasting, dark meat, meat only, cooked, roasted','5120','8',NULL,NULL,NULL),
    (31,4,'Chicken, heart, all classes, raw','5025','8',NULL,NULL,NULL),
    (32,4,'Fish, blackfish, whole (Alaska Native)','35016','8',NULL,NULL,NULL),
    (33,4,'Fish, herring, Pacific, flesh, air-dried, packed in oil (Alaska Native)','35042','8',NULL,NULL,NULL),
    (34,4,'Chicken, broilers or fryers, breast, meat only, cooked, rotisserie, original seasoning','5342','8',NULL,NULL,NULL),
    (35,4,'Snacks, SUNKIST, SUNKIST Fruit Roll, strawberry, with vitamins A, C, and E','19273','8',NULL,NULL,NULL),
    (36,4,'Milk, buttermilk, fluid, whole','1230','8',NULL,NULL,NULL),
    (37,4,'Nuts, chestnuts, european, roasted','12167','8',NULL,NULL,NULL),
    (38,4,'Boysenberries, canned, heavy syrup','9056','8',NULL,NULL,NULL),
    (39,4,'SILK Chocolate, soymilk','16237','8',NULL,NULL,NULL),
    (40,4,'Chewing gum','19163','8',NULL,NULL,NULL),
    (41,4,'Pizza rolls, frozen, unprepared','32012','8',NULL,NULL,NULL),
    (42,4,'Game meat, rabbit, domesticated, composite of cuts, raw','17177','8',NULL,NULL,NULL),
    (43,4,'Fish, tuna, light, canned in water, without salt, drained solids','15184','8',NULL,NULL,NULL),
    (44,4,'Cereals, corn grits, yellow, regular and quick, enriched, cooked with water, without salt','8164','8',NULL,NULL,NULL),
    (45,4,'KEEBLER, ZESTA, Export Sodas Crackers','28255','8',NULL,NULL,NULL),
    (46,4,'Cereals ready-to-eat, KELLOGG, KELLOGG''S SPECIAL K Blueberry','8603','8',NULL,NULL,NULL),
    (47,4,'Beef, loin, top sirloin cap steak, boneless, separable lean and fat, trimmed to 1/8\ fat',' all grades',' raw"','23281',8,NULL),
    (48,4,'English muffins, plain, unenriched, with calcium propionate (includes sourdough)','18438','8',NULL,NULL,NULL),
    (49,4,'Beef, cured, breakfast strips, cooked','13345','8',NULL,NULL,NULL),
    (50,4,'Beef, brisket, flat half, separable lean and fat, trimmed to 1/8\ fat',' all grades',' raw"','13805',8,NULL),
    (51,4,'Nuts, mixed nuts, oil roasted, without peanuts, without salt added','12138','8',NULL,NULL,NULL),
    (52,4,'Infant formula, MEAD JOHNSON, ENFAMIL, NUTRAMIGEN, with iron, powder, not reconstituted','3814','8',NULL,NULL,NULL),
    (53,4,'Beverages, Energy drink, AMP','14625','8',NULL,NULL,NULL),
    (54,4,'Pasta mix, Italian four cheese lasagna, unprepared','32017','8',NULL,NULL,NULL),
    (55,4,'Tomato products, canned, sauce, with tomato tidbits','11559','8',NULL,NULL,NULL),
    (56,4,'Tomatoes, red, ripe, canned, packed in tomato juice, no salt added','11885','8',NULL,NULL,NULL),
    (57,4,'Beef, round, top round roast, boneless, separable lean only, trimmed to 0\ fat',' all grades',' cooked',' roasted"',23378,8),
    (58,4,'Beef, chuck, arm pot roast, separable lean only, trimmed to 1/8\ fat',' choice',' raw"','23612',8,NULL),
    (59,4,'Sausage, Italian, pork, cooked','7089','8',NULL,NULL,NULL),
    (60,4,'Cereals ready-to-eat, MALT-O-MEAL, Cocoa DYNO-BITES','8495','8',NULL,NULL,NULL),
    (61,4,'Fast foods, hotdog, with chili','21119','8',NULL,NULL,NULL),
    (62,4,'Soup, cream of mushroom, canned, prepared with equal volume low fat (2%) milk','6243','8',NULL,NULL,NULL),
    (63,4,'Fish, pike, walleye, raw','15064','8',NULL,NULL,NULL),
    (64,4,'Crustaceans, crab, blue, raw','15139','8',NULL,NULL,NULL),
    (65,4,'Cornmeal, degermed, enriched, white','20322','8',NULL,NULL,NULL),
    (66,4,'Refried beans, canned, fat-free','16172','8',NULL,NULL,NULL),
    (67,4,'Snacks, granola bars, soft, coated, milk chocolate coating, peanut butter','19026','8',NULL,NULL,NULL),
    (68,4,'Fish, halibut, raw, with skin (Alaska Native)','35149','8',NULL,NULL,NULL),
    (69,4,'Beef, rib, small end (ribs 10-12), separable lean only, trimmed to 0\ fat',' select',' cooked',' broiled"',13396,8),
    (70,4,'Beef, round, full cut, separable lean only, trimmed to 1/4\ fat',' select',' cooked',' broiled"',13158,8),
    (71,4,'Cereals, corn grits, white, regular and quick, enriched, dry','8090','8',NULL,NULL,NULL),
    (72,4,'Liver cheese, pork','7040','8',NULL,NULL,NULL),
    (73,4,'Sorghum flour, whole-grain','20648','8',NULL,NULL,NULL),
    (74,4,'Beef, round, eye of round, roast, separable lean and fat, trimmed to 1/8\ fat',' choice',' raw"','13879',8,NULL),
    (75,4,'Puddings, coconut cream, dry mix, instant, prepared with 2% milk','19191','8',NULL,NULL,NULL),
    (76,4,'Beverages, coffee, brewed, breakfast blend','14180','8',NULL,NULL,NULL),
    (77,4,'Rice, white, medium-grain, cooked, unenriched','20451','8',NULL,NULL,NULL),
    (78,4,'Cookies, vanilla wafers, lower fat','18212','8',NULL,NULL,NULL),
    (79,4,'Soup, potato ham chowder, chunky, ready-to-serve, single brand','6728','8',NULL,NULL,NULL),
    (80,4,'Pork, cured, ham -- water added, slice, bone-in, separable lean only, unheated','10886','8',NULL,NULL,NULL),
    (81,4,'Beef, ground, 90% lean meat / 10% fat, raw','23562','8',NULL,NULL,NULL),
    (82,4,'Snacks, potato chips, made from dried potatoes (preformed), multigrain','25063','8',NULL,NULL,NULL),
    (83,4,'Mushrooms, shiitake, stir-fried','11267','8',NULL,NULL,NULL),
    (84,4,'Beef, composite of trimmed retail cuts, separable lean and fat, trimmed to 0\ fat',' all grades',' cooked"','13361',8,NULL),
    (85,4,'Gelatin desserts, dry mix, reduced calorie, with aspartame, added phosphorus, potassium, sodium, vitamin C','19703','5',NULL,NULL,NULL),
    (86,4,'Pork, fresh, enhanced, loin, tenderloin, separable lean only, cooked, roasted','10943','5',NULL,NULL,NULL),
    (87,4,'DOMINO''S 14\ Cheese Pizza',' Classic Hand-Tossed Crust"','21277','5',NULL,NULL),
    (88,4,'Formulated bar, MARS SNACKFOOD US, SNICKERS MARATHON Double Chocolate Nut Bar','25006','5',NULL,NULL,NULL);
