.read diet_optimizer_DB/dietoptforserver/fill_cat_1.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_2_3.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_4.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_5.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_6.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_7.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_8.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_9.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_10.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_11_v1.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_11_v2.sql
.read diet_optimizer_DB/dietoptforserver/fill_cat_12.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_13.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_14.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_15.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_16.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_17.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_18.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_19.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_20.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_21.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_22.sql
.read diet_optimizer_DB/dietoptforserver/fill_part_23.sql